pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "my-vue-app-1"
        NODE_VERSION = "20.16.1"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/huynhgiahuy0409/init-vue.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.withRegistry('', '0d1494df-012e-4867-bc14-3e7ac35ad712') {
                        def app = docker.build("${DOCKER_IMAGE}:${env.BUILD_ID}")
                        app.push()
                    }
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").inside {
                        sh 'npm install'
                        sh 'npm run test'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").inside {
                        sh 'npm run build'
                    }
                    // Các bước deploy ứng dụng lên môi trường production hoặc staging
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build failed!12'
        }
    }
}